name: Deploy VitePress

on:
  push:
    branches: [main]

permissions:
  contents: write # 👈 bắt buộc để push gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ✅ Enable pnpm (fix lỗi pnpm not found)
      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build VitePress
        run: pnpm docs:build

      # ✅ Deploy lên gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
